name: Jacoco Coverage

on:
  pull_request:

permissions:
  contents: read

jobs:
  Jacoco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean build
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/html/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 5
          min-coverage-changed-files: 100

      - run: echo "${{ steps.jacoco.outputs.coverage-overall }}"
      - run: echo "${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Fail Overall Coverage
        if: steps.jacoco.outputs.coverage-overall < 30
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Overal Coverage less than required!')
            github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: '![](https://c.tenor.com/a8EScUYblYwAAAAd/scared-cat-alarmed.gif)\n\nFaltou teste nesse projeto ai'
                        })
      - name: Fail Changed Files Coverage
        if: steps.jacoco.outputs.coverage-changed-files < 30
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Changed Files Coverage less than required!')
            github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: '![](https://c.tenor.com/a8EScUYblYwAAAAd/scared-cat-alarmed.gif)\n\nFaltou teste nesses arquivos ai'
                        })